### ISSUE TITLE
Popolare il README

### ISSUE THREAD

**Issue by iannellog** [AngeloSpadea/Prog_Snake#1]
Riportate nel README.md la specifica che vi abbiamo dato.

Sarebbe anche bene aggiungere in fondo una sezione che spiega lo stato di avanzamento del progetto. Per esempio cose tipo:
- impostata la struttura del codice; definita l'interfaccia di alcune funzioniil programma; non è stata implementata alcuna funzionalità
- completata l'implementazione delle funzioni nel file `gestione_input`; è possibile testare il caricamento della configurazione iniziale; per effettuare il test digitare il seguente comando ...
- è possibile eseguire il programma che però muove lo snake senza controllare se le mosse sono lecite; per effettuare il test digitare il seguente comando ...

ecc.
Naturalmente sempre tutto molto sintetico con l'obiettivo di consentire la comprensione dello stato del progetto senza dover leggere tutto il codice.

**Comment by iannellog** [comment]
Mi pare che non è chiaro cosa può fare un utente per testare il programma.
La sezione del README "Avviare il gioco" è vuota e se provo a eseguire il main.py il programma va in errore perché manca il file di input.
Aggiungete al progetto i file che servono per testare le funzionalità. Va bene usare le unit test, ma non sono sufficienti.
Rispondete a questa issue quando l'avete chiarito se e in che modo posso fare dei test (otre a eseguire gli unit test che però effettuano test parziali e ce ne sono tre che non passano).

**Comment by antoniospadea** [comment]
Abbiamo caricato i file necessari per avviare il programma, per ora sono disponibili le istruzioni per provare il programma con due versioni di campo da gioco e due versioni di mosse. Le istruzioni spiegano come manualmente potranno essere testati. Seguiranno altre versioni di partite che andranno a testare nello specifico le 5 regole da gioco. Inoltre Abbiamo corretto alcuni test ma nel corso di domani prevediamo di completare la correzione di tutti i test.
