### ISSUE TITLE
Impiego delle classi

### ISSUE THREAD

**Issue by iannellog** [AngeloSpadea/Prog_Snake#10]
Nel vostro codice non avete mai usato le classi. 
Valutate se non sia il caso di usarle per modellare alcune delle entità richieste dal gioco.
Per esempio, senza stravolgere l'impostazione che avete dato fino ad ora, potreste usare il design pattern *strategy* per gestire in modo uniforme le due alternative di input (da immagine e da json).
In alternativa, potreste rappresentare il campo di gioco con un unico oggetto che ha come attributi le variabili `food`, `blocks`, `righe`, `colonne`.

**Comment by AngeloSpadea** [comment]
Domani mi ci metto e faccio il pattern strategy

**Comment by AngeloSpadea** [comment]
Ho implementato il pattern strategy. Ora è possibile utilizzare sia i campi in .json che in .png
