### ISSUE TITLE
significato di una condizione in `scontro_coda`

### ISSUE THREAD

**Issue by iannellog** [AngeloSpadea/Prog_Snake#11]
Siete sicuri di cosa significa in Python la condizione (riga 216 del file `funzioni_gioco`):
> posizione_nuova or (segmento1 and segmento2) in corpo 

?
Non sarei tanto sicuro di quale sia la semantica di un operatore logico applocato a delle liste ...
e poi non mi convince l'uso dell'operatore `and`.

Suggerirei di ragionare bene sulla condizione e scriverla in modo più esplicito tenendo conto del tipo delle variabili che usate.

**Comment by AngeloSpadea** [comment]
Sistemato
