### ISSUE TITLE
manca un commit

### ISSUE THREAD

**Issue by iannellog** [AngeloSpadea/Prog_Snake#6]
Da quello che vedo sembra che il file `gestione_input.py` sia stato modificato senza che sia stato effettuato il commit conseguente.
In altre parole se sul mio repository locale digito `git status` ho il messaggio:

> Modifiche non nell'area di staging per il commit:
> > (usa "git add <file>..." per aggiornare gli elementi di cui sarà eseguito il commit)
> (usa "git restore <file>..." per scartare le modifiche nella directory di lavoro)
>	> modificato:             gestione_input.py
>
> nessuna modifica aggiunta al commit (usa "git add" e/o "git commit -a")

verificate se manca un commit.

**Comment by AngeloSpadea** [comment]
A me risulta caricato tutto

**Comment by iannellog** [comment]
ora è tutto ok, probabilmente avevo sporcato io il repository locale
