### ISSUE TITLE
Funzione `controlla`

### ISSUE THREAD

**Issue by iannellog** [AngeloSpadea/Prog_Snake#7]
Il risultato restituito dalla funzione `scontro_coda` non viene usato. Questo non sembra corretto: se il valore logicoo non viene usato che senso ha restituirlo? E di conseguenza a cosa serve la funzione `scontro_coda`?
Correggere o chiarire

Mettere un commento al ramo `else` (riga 111) che espliciti quando viene eseguito quel ramo.

**Comment by MartinaBertazzoni** [comment]
Il risultato della funzione scontro_coda deve essere utilizzato per gestire la situazione in cui il serpente  si scontra contro la sua stessa coda o tenta di attraversarla in direzione diagonale. Qualora tali situazioni si dovessero verificare, la funzione scontro_coda restituirebbe il risultato True che deve essere utilizzato nella funzione controlla per far terminare il gioco.
Tuttavia, la funzione controlla è ancora incompleta. Quando sarà terminata, gestirà la situazione sopra illustrata.

**Comment by iannellog** [comment]
Va bene, ma sarebbe sembre bene che il codice mantenga una certa coerenza logica, anche se non implementa tutte le funzionalità. Se ho una funzione che restituisce qualcosa e la uso dovrei usare ciò che restituisce. Se non sono ancora pronto a usare il risultato evito di chiamarla. Di fatto la chiamata alla funzione `scontro_coda` non produce alcun risultato e la chamata potrebbe essere eliminata senza problemi, salvo poi inseririla quanto sarà pronta per essere effettivamente usata.
Comunque tenete presente la issue iniziale quando la funzione `scontro_coda` sarà completata.

**Comment by AngeloSpadea** [comment]
scontro_coda non era legata ad alcun parametro quando finiamo bene la funzione la inseriremo nel modo corretto
