### ISSUE TITLE
Funzione `scontro_coda`

### ISSUE THREAD

**Issue by iannellog** [AngeloSpadea/Prog_Snake#8]
Aggiungere dei commenti che spieghino il senso delle espressioni e delle condizioni presenti nel codice in modo da evitare che chi legge debba ricostruire la logica che li ha generati. Il codice attuale è di fatto incomprensibile per chi non l'ha scritto ed è pertanto difficile anche capire se è corretto.

**Comment by MartinaBertazzoni** [comment]
I commenti della funzione scontro_coda sono stati modificati in modo da facilitarne la comprensione e poterne verificare la correttezza.
