### ISSUE TITLE
Usare i test forniti

### ISSUE THREAD

**Issue by iannellog** [AngeloSpadea/Prog_Snake#9]
Per eseguire i test forniti da noi dovete modificare la riga 80 del file `gestione_input.py` come segue.
Al posto di:

> black_image.save("output/"+final_field)

dovete scrivere:

> black_image.save("data/"+final_field)

Facendo così il vostro codice passa test 02 (non ancora gli altri). 
Suggerirei anche di aggiungere a `.gitignore` la riga seguente:

data/*

**Comment by AngeloSpadea** [comment]
- ho messo tutti i file necessari in data così non ho più il problema delle directory 
- ho eliminato quelle inutili
- ho aggiornato il gitignore
